-- MySQL Script generated by MySQL Workbench
-- Sat Nov 17 16:24:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Mock_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mock_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mock_Database` DEFAULT CHARACTER SET utf8 ;
USE `Mock_Database` ;

-- -----------------------------------------------------
-- Table `Mock_Database`.`Camps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`Camps` (
  `campID` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`campID`),
  UNIQUE INDEX `campID_UNIQUE` (`campID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mock_Database`.`Campers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`Campers` (
  `camperID` VARCHAR(45) NOT NULL,
  `campID` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `preferred_name` VARCHAR(45) NULL,
  `gender` VARCHAR(2) NOT NULL,
  `dob` DATE NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `height_cm` INT NOT NULL,
  `weight_lbs` INT NOT NULL,
  `health_card_num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`camperID`),
  UNIQUE INDEX `camperID_UNIQUE` (`camperID` ASC) VISIBLE,
  INDEX `campID_idx` (`campID` ASC) VISIBLE,
  UNIQUE INDEX `heal_card_num_UNIQUE` (`health_card_num` ASC) VISIBLE,
  CONSTRAINT `campID`
    FOREIGN KEY (`campID`)
    REFERENCES `Mock_Database`.`Camps` (`campID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mock_Database`.`Allergies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`Allergies` (
  `allergyID` VARCHAR(45) NOT NULL,
  `camperID` VARCHAR(45) NOT NULL,
  `ephinephrine_cd` VARCHAR(2) NOT NULL,
  `allgergen` VARCHAR(45) NOT NULL,
  `reaction` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`allergyID`),
  INDEX `camperID_idx` (`camperID` ASC) VISIBLE,
  UNIQUE INDEX `allergyID_UNIQUE` (`allergyID` ASC) VISIBLE,
  CONSTRAINT `camperID`
    FOREIGN KEY (`camperID`)
    REFERENCES `Mock_Database`.`Campers` (`camperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mock_Database`.`Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`Medications` (
  `medID` VARCHAR(45) NOT NULL,
  `camperID` VARCHAR(45) NOT NULL,
  `medication` VARCHAR(45) NOT NULL,
  `dose` VARCHAR(45) NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  `session` VARCHAR(45) NOT NULL,
  `details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`medID`),
  INDEX `camperID_idx` (`camperID` ASC) VISIBLE,
  UNIQUE INDEX `medID_UNIQUE` (`medID` ASC) VISIBLE,
  CONSTRAINT `camperID`
    FOREIGN KEY (`camperID`)
    REFERENCES `Mock_Database`.`Campers` (`camperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mock_Database`.`MedicationAdminLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`MedicationAdminLog` (
  `logID` VARCHAR(45) NOT NULL,
  `medID` VARCHAR(45) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `session` VARCHAR(45) NOT NULL,
  `administered_cd` VARCHAR(1) NULL,
  PRIMARY KEY (`logID`),
  INDEX `medID_idx` (`medID` ASC) VISIBLE,
  UNIQUE INDEX `logID_UNIQUE` (`logID` ASC) VISIBLE,
  CONSTRAINT `medID`
    FOREIGN KEY (`medID`)
    REFERENCES `Mock_Database`.`Medications` (`medID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mock_Database`.`EmergencyContacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`EmergencyContacts` (
  `emerg_contID` VARCHAR(45) NOT NULL,
  `camperID` VARCHAR(45) NOT NULL,
  `contact_name` VARCHAR(45) NOT NULL,
  `contact_phone` VARCHAR(45) NOT NULL,
  `contact_relationship` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`emerg_contID`),
  INDEX `camperID_idx` (`camperID` ASC) VISIBLE,
  CONSTRAINT `camperID`
    FOREIGN KEY (`camperID`)
    REFERENCES `Mock_Database`.`Campers` (`camperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mock_Database`.`Waviers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mock_Database`.`Waviers` (
  `waiverID` VARCHAR(45) NOT NULL,
  `camperID` VARCHAR(45) NOT NULL,
  `signed` VARCHAR(2) NOT NULL,
  `signed_date` DATE NOT NULL,
  `signed_initials` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`waiverID`),
  UNIQUE INDEX `waiverID_UNIQUE` (`waiverID` ASC) VISIBLE,
  INDEX `camperID_idx` (`camperID` ASC) VISIBLE,
  CONSTRAINT `camperID`
    FOREIGN KEY (`camperID`)
    REFERENCES `Mock_Database`.`Campers` (`camperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
